### ISSUE TITLE
Alarm sound does not work with Pulseaudio

### ISSUE THREAD

**Issue by FlxB2** [AmyAssist/Amy#219]
Here is the error trace: 
```
21:44:40.117 [Thread-1] ERROR d.u.i.a.amy.core.console.Console - Error while handling input [alarm, set, alarm, at, 20, oh, 20]
java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:453)
	at de.unistuttgart.iaas.amyassist.amy.plugin.alarmclock.AlarmBeepService.init(AlarmBeepService.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at de.unistuttgart.iaas.amyassist.amy.core.di.util.Util.callAnnotatedMethods(Util.java:151)
	at de.unistuttgart.iaas.amyassist.amy.core.di.util.Util.postConstruct(Util.java:120)
	at de.unistuttgart.iaas.amyassist.amy.core.di.provider.ClassServiceProvider.createService(ClassServiceProvider.java:148)
	at de.unistuttgart.iaas.amyassist.amy.core.di.provider.ClassServiceProvider.getService(ClassServiceProvider.java:123)
	at de.unistuttgart.iaas.amyassist.amy.core.di.ServiceProviderServiceFactory.build(ServiceProviderServiceFactory.java:61)
	at de.unistuttgart.iaas.amyassist.amy.core.di.provider.ClassServiceProvider.createService(ClassServiceProvider.java:141)
	at de.unistuttgart.iaas.amyassist.amy.core.di.provider.ClassServiceProvider.getService(ClassServiceProvider.java:123)
	at de.unistuttgart.iaas.amyassist.amy.core.di.ServiceProviderServiceFactory.build(ServiceProviderServiceFactory.java:61)
	at de.unistuttgart.iaas.amyassist.amy.core.di.DependencyInjection.getService(DependencyInjection.java:168)
	at de.unistuttgart.iaas.amyassist.amy.core.di.DependencyInjection.getService(DependencyInjection.java:159)
	at de.unistuttgart.iaas.amyassist.amy.core.di.DependencyInjection.inject(DependencyInjection.java:250)
	at de.unistuttgart.iaas.amyassist.amy.core.di.DependencyInjection.createAndInitialize(DependencyInjection.java:290)
	at de.unistuttgart.iaas.amyassist.amy.core.speech.result.handler.SpeechCommandHandler.call(SpeechCommandHandler.java:126)
	at de.unistuttgart.iaas.amyassist.amy.core.speech.result.handler.SpeechCommandHandler.handleSpeechInput(SpeechCommandHandler.java:121)
	at de.unistuttgart.iaas.amyassist.amy.core.NaturalLanaguageInputHandlerService.lambda$0(NaturalLanaguageInputHandlerService.java:60)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by FlxB2** [comment]
fixed with pr #220
